### ISSUE TITLE
怎么跳过某一章节

### ISSUE THREAD

**Issue by lindongyuan** [kongjake/autoPlay91Huayi#1]
非常好用，但是没一次性学完的话，不能继续上次的课程，应该怎么处理？

**Comment by kongjake** [comment]
代码里有一行
var beginCourseName = '碳达峰碳中和实现的科技路径';
把碳达峰碳中和实现的科技路径改成你要播放的课程名字

**Comment by lindongyuan** [comment]
> 
谢谢，已经解决。
